spring:
  profiles:
    active: dev
  freemarker:
    allow-request-override: false
    allow-session-override: false
    cache: false
    charset: utf-8
    check-template-location: true
    content-type: text/html
    enabled: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    prefer-file-system-access: true
    suffix: .ftl
    template-loader-path: ["classpath:/templates/"]
  aop:
    auto: true
