server:
  port: 8080

spring:
  datasource:
    username: gree
    password: Gree#098
    url: jdbc:mysql://rm-bp148dnev87ekxu18o.mysql.rds.aliyuncs.com:3306/db_company_webpage?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.zhiwei.po

#showSql
logging:
  level:
    com:
      zhiwei:
        dao : debug
